version: "3.9"
services:
  db:
    container_name: postgres-database
    image: postgres:13.4-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M
  # admin panel for database
  adminer:
    image: adminer
    ports:
      - 8080:8080
